name: singularity-deploy-test

# run on creation of a release tag
on:
  pull_request: []

jobs:
  builder:
    name: Test Container Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: eWaterCycle/setup-singularity@v6
        with:
          singularity-version: 3.7.1
      - name: Build the singularity containers
        run: |
            repo=$(echo "${GITHUB_REPOSITORY/\//-}")

            # For each Singularity* container, build based on the prefix (tag) 
            for recipe in $(ls *.sif); do
                echo "Building $recipe"
                tag=$(echo "${recipe/\.sif/}")
                # If we find empty, use latest
                if [ "$tag" == "Singularity" ]; then
                    tag=latest
                fi
                release=$(cat VERSION)
                # Build the container and name by tag
                echo "Tag is $tag"
                echo "Version is $release"
                # container="$repo:$tag" # renaming
                container="$tag_$release$"
                singularity build --fakeroot container "$recipe"
                if [ "$?" == "0" ]; then
                    echo "Successfully built container $container."                
                    mv container "$container"
                else
                    echo "There was an issue building $container."          
                fi
            done
      - name: Run Additional Tests
        run: |
          echo "Run any additional tests here."
